Repository FC-Palette/Palette-FE, pull requests merged in 2023-09, with the labels that each got.

#53 [FIX] 미리보기 페이지 컴포넌트 props로 넘기도록 수정
  src/components/career/create/isUserInfo/stepPreview/GetMeetingCategory.tsx
  src/components/career/create/isUserInfo/stepPreview/GetMeetingInfo.tsx
  src/components/career/create/isUserInfo/stepPreview/GetThumbnail.tsx
  src/components/career/create/isUserInfo/stepPreview/GetTitleAndDescription.tsx
  src/components/career/create/isUserInfo/stepPreview/StepPreviewCard.tsx
Labels: enhancement

#70 [FIX] 공통헤더 min-height수정 및 index.html meta속성 조정 + 채팅 레이아웃 수정사항
  index.html
  src/components/chat/chaton/ChatInfo.tsx
  src/components/common/Header.tsx
  src/pages/ChatOn.tsx
Labels: bug

#73 [FIX] 성장해요 페이지 반응형으로 수정
  src/components/career/create/ifEmptyUserInfo/ProfileEnterWrap.tsx
  src/components/career/main/CareerMainCard.tsx
  src/components/career/paricipate/condition_met/common/IsApprovedJoinMeetingFooter.tsx
  src/components/career/paricipate/condition_met/common/JoinMeetingStepOneTitle.tsx
  src/components/career/paricipate/condition_met/isApproved/IsApprovedJoinMeetingStepCompleteCard.tsx
  src/components/career/paricipate/condition_met/isApproved/IsApprovedJoinMeetingStepOneCard.tsx
  src/components/career/paricipate/condition_met/isApproved/IsApprovedJoinMeetingStepTwoCard.tsx
  src/components/career/paricipate/condition_met/isApproved/JoinMeetingStepCompleteTitle.tsx
  src/components/career/paricipate/condition_met/isApproved/JoinMeetingStepTwoTextField.tsx
  src/components/career/paricipate/condition_met/isApproved/JoinMeetingStepTwoTitle.tsx
  src/components/career/paricipate/condition_met/isNotApproved/IsNotApprovedJoinMeetingStepOneCard.tsx
  src/components/career/paricipate/getDetail/GetDetailCard.tsx
  src/components/career/paricipate/getDetail/GetDetailCategoryChips.tsx
  src/components/career/paricipate/getDetail/GetDetailFooterAndButton.tsx
  src/components/career/paricipate/getDetail/GetDetailHeader.tsx
  src/components/career/paricipate/getDetail/GetDetailManagerInfo.tsx
  src/components/career/paricipate/getDetail/GetDetailMeetupInfo.tsx
  src/components/career/paricipate/getDetail/GetDetailMemberSeeMore.tsx
  src/components/career/paricipate/getDetail/GetDetailMembersInfo.tsx
  src/components/career/paricipate/getDetail/GetDetailSimilarMeetupInfo.tsx
  src/components/career/paricipate/getDetail/GetDetailStats.tsx
  src/components/career/paricipate/getDetail/GetDetailThumbnail.tsx
  src/components/career/paricipate/getDetail/GetDetailTitleAndDescription.tsx
  src/components/common/CommonAddIcon.tsx
  src/components/common/FilterBar.tsx
  src/components/common/ModalButtons.tsx
  src/components/common/StepProgressBar.tsx
  src/components/common/index.ts
  src/constants/career/careerSubHeaderText.ts
  src/constants/career/createModalStateText.ts
  src/pages/CareerIsApprovedJoinMeeting.tsx
  src/pages/CareerIsNotApprovedJoinMeeting.tsx
  src/pages/CareerIsNotUserInfo.tsx
Labels: enhancement

#75 [FEAT]: 버튼 및 공동구매, 중고거래 레이아웃수정
  src/components/career/create/isUserInfo/stepPreview/GetTitleAndDescription.tsx
  src/components/career/create/isUserInfo/stepPreview/StepPreviewCard.tsx
  src/components/trades/README.md
  src/components/trades/preview/common/PreviewFooter.tsx
  src/components/trades/preview/previewsecondhand/SecondHandPre.tsx
  src/components/trades/preview/previewtrades/PurchasePreview.tsx
  src/constants/trades/modalText.ts
  src/pages/GroupUpload.tsx
  src/pages/README.md
  src/pages/SecondHandUpload.tsx
Labels: enhancement

#76 [FEAT] 메시지 공유 컴포넌트 타입 추가 및 공용 axios instances 파일 생성
  src/api/axios.ts
  src/components/MediaQuery.tsx
  src/components/chat/chaton/ChatField.tsx
  src/components/chat/chaton/ChatInfo.tsx
  src/components/chat/chaton/SubjectDetail.tsx
  src/constants/chat/chatTexts.ts
Labels: enhancement

#78 [FIX] 성장해요 레이아웃 재 수정 + 승인 페이지 제작중
  src/components/career/create/common/MeetingsCreateFooter.tsx
  src/components/career/create/common/MeetingsPreviewFooter.tsx
  src/components/career/create/isUserInfo/stepOne/MeetupTypeSelector2.tsx
  src/components/career/create/isUserInfo/stepOne/RoleAndGenderSelector.tsx
  src/components/career/create/isUserInfo/stepPreview/GetThumbnail.tsx
  src/components/career/create/isUserInfo/stepPreview/PreviewMember.tsx
  src/components/career/create/isUserInfo/stepThree/MemberApprovalMethodSelector.tsx
  src/components/career/paricipate/condition_met/common/IsApprovedJoinMeetingFooter.tsx
  src/components/career/paricipate/confirm/CareerMeetingConfirmCard.tsx
  src/components/career/paricipate/confirm/CareerMeetingConfirmTitle.tsx
  src/components/career/paricipate/confirm/index.ts
  src/components/career/paricipate/getDetail/GetDetailCard.tsx
  src/components/career/paricipate/getDetail/GetDetailFooterAndButton.tsx
  src/components/career/paricipate/getDetail/GetDetailManagerInfo.tsx
  src/components/career/paricipate/getDetail/GetDetailMemberSeeMore.tsx
  src/components/career/paricipate/getDetail/GetDetailMembersInfo.tsx
  src/components/career/paricipate/getDetail/GetDetailThumbnail.tsx
  src/components/career/paricipate/index.ts
  src/pages/CareerIsApprovedJoinMeeting.tsx
  src/pages/CareerIsNotApprovedJoinMeeting.tsx
  src/pages/CareerMain.tsx
  src/pages/CareerMeetingConfirm.tsx
  src/pages/CareerMeetingsCreate.tsx
  src/pages/Router.tsx
  src/pages/index.ts
Labels: documentation

#86 fix: tsc 오류 해결
  src/components/career/main/CareerMainFilterBar.tsx
  src/components/career/main/CareerMainItemsWrap.tsx
  src/components/career/paricipate/getDetail/GetDetailFooterAndButtonHost.tsx
  src/components/trades/cardlist/purchasecard/GroupPurchaseList.tsx
  src/components/trades/cardlist/secondhandcard/SecondHandList.tsx
  src/types/filterBarProps.ts
Labels: documentation

#87 style: 공동구매, 중고거래 리스트 그리드적용 및 UI수정
  src/api/trades/groupPurchaseListApi.ts
  src/api/trades/index.ts
  src/api/trades/secondHandListApi.ts
  src/components/common/IconMapping.tsx
  src/components/common/SideBar.tsx
  src/components/common/index.ts
  src/components/trades/cardlist/common/TradesCard.tsx
  src/components/trades/cardlist/common/TradesCategory.tsx
  src/components/trades/cardlist/common/TradesImage.tsx
  src/components/trades/cardlist/common/TradesLikeCount.tsx
  src/components/trades/cardlist/common/TradesPrice.tsx
  src/components/trades/cardlist/common/TradesTime.tsx
  src/components/trades/cardlist/common/TradesTitle.tsx
  src/components/trades/cardlist/common/TradesViews.tsx
  src/components/trades/cardlist/purchasecard/GroupPurchaseList.tsx
  src/components/trades/cardlist/secondhandcard/SecondHandList.tsx
  src/components/trades/preview/previewsecondhand/SecondHandPre.tsx
  src/components/trades/upload/common/UploadInputDetail.tsx
  src/components/trades/upload/common/UploadOption.tsx
  src/components/trades/upload/index.ts
  src/components/trades/upload/uploadpurchase/Account.tsx
  src/components/trades/upload/uploadpurchase/PurchaseImages.tsx
  src/components/trades/upload/uploadpurchase/PurchaseUploadList.tsx
  src/components/trades/upload/uploadsecondhand/SecondHandDay.tsx
  src/components/trades/upload/uploadsecondhand/SecondHandImages.tsx
  src/components/trades/upload/uploadsecondhand/SecondHandOption.tsx
  src/components/trades/upload/uploadsecondhand/SecondHandTime.tsx
  src/components/trades/upload/uploadsecondhand/SecondHandUploadList.tsx
  src/constants/trades/inputText.ts
  src/constants/trades/modalText.ts
  src/pages/GroupPurchase.tsx
  src/pages/GroupUpload.tsx
  src/pages/SecondHand.tsx
  src/pages/SecondHandUpload.tsx
  src/public/bankLogos/citibank.png
  src/public/bankLogos/cubank.png
  src/public/bankLogos/dgbank.png
  src/public/bankLogos/epostbank.png
  src/public/bankLogos/hanabank.png
  src/public/bankLogos/ibkbank.png
  src/public/bankLogos/index.ts
  src/public/bankLogos/kakaobank.png
  src/public/bankLogos/kbank.png
  src/public/bankLogos/kbbank.png
  src/public/bankLogos/kjbank.png
  src/public/bankLogos/knbank.png
  src/public/bankLogos/mgbank.png
  src/public/bankLogos/nhbank.png
  src/public/bankLogos/ourbank.png
  src/public/bankLogos/scbank.png
  src/public/bankLogos/shinhanbank.png
  src/public/bankLogos/suhyupbank.png
  src/public/bankLogos/tossbank.png
  src/public/index.ts
  src/recoil/tradescreateglobalstate.ts
  src/types/filterBarProps.ts
  src/types/trades/tradesUploadProps.ts
  tsconfig.json
Labels: enhancement

#93 [FEAT] 개인 채팅 상단 주제 없을 시 상태 추가, 스타일 추가 정리
  src/components/chat/chatann/ChatAnnListItem.tsx
  src/components/chat/chaton/AccountInfo.tsx
  src/components/chat/chaton/ChatAnn.tsx
  src/components/chat/chaton/ChatField.tsx
  src/components/chat/chaton/ChatInfo.tsx
  src/components/chat/chaton/ChatMembers.tsx
  src/components/chat/chaton/Member.tsx
  src/components/chat/chaton/MessageItem.tsx
  src/components/chat/chaton/MsgActions.tsx
  src/components/chat/chaton/Recipient.tsx
  src/components/chat/chaton/SendFile.tsx
  src/components/chat/chaton/SubjectDetail.tsx
  src/components/chat/chaton/ToChatList.tsx
  src/recoil/atoms.ts
Labels: documentation, enhancement

#97 [FIX] useCabllback dependency 에러 해결
  src/components/chat/chaton/ChatField.tsx
  src/components/chat/chaton/ChatMembers.tsx
Labels: bug, documentation
